use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Language {
    Afrikaans,
    Albanian,
    Amharic,
    Arabic,
    Armenian,
    Assamese,
    Aymara,
    Azerbaijani,
    Bambara,
    Basque,
    Belarusian,
    Bengali,
    Bhojpuri,
    Bosnian,
    Bulgarian,
    Catalan,
    Cebuano,
    ChineseSimplified,
    ChineseTraditional,
    Corsican,
    Croatian,
    Czech,
    Danish,
    Dhivehi,
    Dogri,
    Dutch,
    English,
    Esperanto,
    Estonian,
    Ewe,
    Filipino,
    Finnish,
    French,
    Frisian,
    Galician,
    Georgian,
    German,
    Greek,
    Guarani,
    Gujarati,
    HaitianCreole,
    Hausa,
    Hawaiian,
    Hebrew,
    Hindi,
    Hmong,
    Hungarian,
    Icelandic,
    Igbo,
    Ilocano,
    Indonesian,
    Irish,
    Italian,
    Japanese,
    Javanese,
    Kannada,
    Kazakh,
    Khmer,
    Kinyarwanda,
    Konkani,
    Korean,
    Krio,
    Kurdish,
    KurdishSorani,
    Kyrgyz,
    Lao,
    Latin,
    Latvian,
    Lingala,
    Lithuanian,
    Luganda,
    Luxembourgish,
    Macedonian,
    Maithili,
    Malagasy,
    Malay,
    Malayalam,
    Maltese,
    Maori,
    Marathi,
    Meiteilon,
    Mizo,
    Mongolian,
    Myanmar,
    Nepali,
    Norwegian,
    Nyanja,
    Odia,
    Oromo,
    Pashto,
    Persian,
    Polish,
    Portuguese,
    Punjabi,
    Quechua,
    Romanian,
    Russian,
    Samoan,
    Sanskrit,
    ScotsGaelic,
    Sepedi,
    Serbian,
    Sesotho,
    Shona,
    Sindhi,
    Sinhala,
    Slovak,
    Slovenian,
    Somali,
    Spanish,
    Sundanese,
    Swahili,
    Swedish,
    Tajik,
    Tamil,
    Tatar,
    Telugu,
    Thai,
    Tigrinya,
    Tsonga,
    Turkish,
    Turkmen,
    Twi,
    Ukrainian,
    Urdu,
    Uyghur,
    Uzbek,
    Vietnamese,
    Welsh,
    Xhosa,
    Yiddish,
    Yoruba,
    Zulu,
}

impl Language {
    pub fn all() -> Vec<Language> {
        vec![
            Language::Afrikaans,
            Language::Albanian,
            Language::Amharic,
            Language::Arabic,
            Language::Armenian,
            Language::Assamese,
            Language::Aymara,
            Language::Azerbaijani,
            Language::Bambara,
            Language::Basque,
            Language::Belarusian,
            Language::Bengali,
            Language::Bhojpuri,
            Language::Bosnian,
            Language::Bulgarian,
            Language::Catalan,
            Language::Cebuano,
            Language::ChineseSimplified,
            Language::ChineseTraditional,
            Language::Corsican,
            Language::Croatian,
            Language::Czech,
            Language::Danish,
            Language::Dhivehi,
            Language::Dogri,
            Language::Dutch,
            Language::English,
            Language::Esperanto,
            Language::Estonian,
            Language::Ewe,
            Language::Filipino,
            Language::Finnish,
            Language::French,
            Language::Frisian,
            Language::Galician,
            Language::Georgian,
            Language::German,
            Language::Greek,
            Language::Guarani,
            Language::Gujarati,
            Language::HaitianCreole,
            Language::Hausa,
            Language::Hawaiian,
            Language::Hebrew,
            Language::Hindi,
            Language::Hmong,
            Language::Hungarian,
            Language::Icelandic,
            Language::Igbo,
            Language::Ilocano,
            Language::Indonesian,
            Language::Irish,
            Language::Italian,
            Language::Japanese,
            Language::Javanese,
            Language::Kannada,
            Language::Kazakh,
            Language::Khmer,
            Language::Kinyarwanda,
            Language::Konkani,
            Language::Korean,
            Language::Krio,
            Language::Kurdish,
            Language::KurdishSorani,
            Language::Kyrgyz,
            Language::Lao,
            Language::Latin,
            Language::Latvian,
            Language::Lingala,
            Language::Lithuanian,
            Language::Luganda,
            Language::Luxembourgish,
            Language::Macedonian,
            Language::Maithili,
            Language::Malagasy,
            Language::Malay,
            Language::Malayalam,
            Language::Maltese,
            Language::Maori,
            Language::Marathi,
            Language::Meiteilon,
            Language::Mizo,
            Language::Mongolian,
            Language::Myanmar,
            Language::Nepali,
            Language::Norwegian,
            Language::Nyanja,
            Language::Odia,
            Language::Oromo,
            Language::Pashto,
            Language::Persian,
            Language::Polish,
            Language::Portuguese,
            Language::Punjabi,
            Language::Quechua,
            Language::Romanian,
            Language::Russian,
            Language::Samoan,
            Language::Sanskrit,
            Language::ScotsGaelic,
            Language::Sepedi,
            Language::Serbian,
            Language::Sesotho,
            Language::Shona,
            Language::Sindhi,
            Language::Sinhala,
            Language::Slovak,
            Language::Slovenian,
            Language::Somali,
            Language::Spanish,
            Language::Sundanese,
            Language::Swahili,
            Language::Swedish,
            Language::Tajik,
            Language::Tamil,
            Language::Tatar,
            Language::Telugu,
            Language::Thai,
            Language::Tigrinya,
            Language::Tsonga,
            Language::Turkish,
            Language::Turkmen,
            Language::Twi,
            Language::Ukrainian,
            Language::Urdu,
            Language::Uyghur,
            Language::Uzbek,
            Language::Vietnamese,
            Language::Welsh,
            Language::Xhosa,
            Language::Yiddish,
            Language::Yoruba,
            Language::Zulu,
        ]
    }

    pub fn name(&self) -> &'static str {
        match self {
            Language::Afrikaans => "Afrikaans",
            Language::Albanian => "Albanian",
            Language::Amharic => "Amharic",
            Language::Arabic => "Arabic",
            Language::Armenian => "Armenian",
            Language::Assamese => "Assamese",
            Language::Aymara => "Aymara",
            Language::Azerbaijani => "Azerbaijani",
            Language::Bambara => "Bambara",
            Language::Basque => "Basque",
            Language::Belarusian => "Belarusian",
            Language::Bengali => "Bengali",
            Language::Bhojpuri => "Bhojpuri",
            Language::Bosnian => "Bosnian",
            Language::Bulgarian => "Bulgarian",
            Language::Catalan => "Catalan",
            Language::Cebuano => "Cebuano",
            Language::ChineseSimplified => "Chinese (Simplified)",
            Language::ChineseTraditional => "Chinese (Traditional)",
            Language::Corsican => "Corsican",
            Language::Croatian => "Croatian",
            Language::Czech => "Czech",
            Language::Danish => "Danish",
            Language::Dhivehi => "Dhivehi",
            Language::Dogri => "Dogri",
            Language::Dutch => "Dutch",
            Language::English => "English",
            Language::Esperanto => "Esperanto",
            Language::Estonian => "Estonian",
            Language::Ewe => "Ewe",
            Language::Filipino => "Filipino",
            Language::Finnish => "Finnish",
            Language::French => "French",
            Language::Frisian => "Frisian",
            Language::Galician => "Galician",
            Language::Georgian => "Georgian",
            Language::German => "German",
            Language::Greek => "Greek",
            Language::Guarani => "Guarani",
            Language::Gujarati => "Gujarati",
            Language::HaitianCreole => "Haitian Creole",
            Language::Hausa => "Hausa",
            Language::Hawaiian => "Hawaiian",
            Language::Hebrew => "Hebrew",
            Language::Hindi => "Hindi",
            Language::Hmong => "Hmong",
            Language::Hungarian => "Hungarian",
            Language::Icelandic => "Icelandic",
            Language::Igbo => "Igbo",
            Language::Ilocano => "Ilocano",
            Language::Indonesian => "Indonesian",
            Language::Irish => "Irish",
            Language::Italian => "Italian",
            Language::Japanese => "Japanese",
            Language::Javanese => "Javanese",
            Language::Kannada => "Kannada",
            Language::Kazakh => "Kazakh",
            Language::Khmer => "Khmer",
            Language::Kinyarwanda => "Kinyarwanda",
            Language::Konkani => "Konkani",
            Language::Korean => "Korean",
            Language::Krio => "Krio",
            Language::Kurdish => "Kurdish",
            Language::KurdishSorani => "Kurdish (Sorani)",
            Language::Kyrgyz => "Kyrgyz",
            Language::Lao => "Lao",
            Language::Latin => "Latin",
            Language::Latvian => "Latvian",
            Language::Lingala => "Lingala",
            Language::Lithuanian => "Lithuanian",
            Language::Luganda => "Luganda",
            Language::Luxembourgish => "Luxembourgish",
            Language::Macedonian => "Macedonian",
            Language::Maithili => "Maithili",
            Language::Malagasy => "Malagasy",
            Language::Malay => "Malay",
            Language::Malayalam => "Malayalam",
            Language::Maltese => "Maltese",
            Language::Maori => "Maori",
            Language::Marathi => "Marathi",
            Language::Meiteilon => "Meiteilon (Manipuri)",
            Language::Mizo => "Mizo",
            Language::Mongolian => "Mongolian",
            Language::Myanmar => "Myanmar (Burmese)",
            Language::Nepali => "Nepali",
            Language::Norwegian => "Norwegian",
            Language::Nyanja => "Nyanja (Chichewa)",
            Language::Odia => "Odia (Oriya)",
            Language::Oromo => "Oromo",
            Language::Pashto => "Pashto",
            Language::Persian => "Persian",
            Language::Polish => "Polish",
            Language::Portuguese => "Portuguese",
            Language::Punjabi => "Punjabi",
            Language::Quechua => "Quechua",
            Language::Romanian => "Romanian",
            Language::Russian => "Russian",
            Language::Samoan => "Samoan",
            Language::Sanskrit => "Sanskrit",
            Language::ScotsGaelic => "Scots Gaelic",
            Language::Sepedi => "Sepedi",
            Language::Serbian => "Serbian",
            Language::Sesotho => "Sesotho",
            Language::Shona => "Shona",
            Language::Sindhi => "Sindhi",
            Language::Sinhala => "Sinhala",
            Language::Slovak => "Slovak",
            Language::Slovenian => "Slovenian",
            Language::Somali => "Somali",
            Language::Spanish => "Spanish",
            Language::Sundanese => "Sundanese",
            Language::Swahili => "Swahili",
            Language::Swedish => "Swedish",
            Language::Tajik => "Tajik",
            Language::Tamil => "Tamil",
            Language::Tatar => "Tatar",
            Language::Telugu => "Telugu",
            Language::Thai => "Thai",
            Language::Tigrinya => "Tigrinya",
            Language::Tsonga => "Tsonga",
            Language::Turkish => "Turkish",
            Language::Turkmen => "Turkmen",
            Language::Twi => "Twi",
            Language::Ukrainian => "Ukrainian",
            Language::Urdu => "Urdu",
            Language::Uyghur => "Uyghur",
            Language::Uzbek => "Uzbek",
            Language::Vietnamese => "Vietnamese",
            Language::Welsh => "Welsh",
            Language::Xhosa => "Xhosa",
            Language::Yiddish => "Yiddish",
            Language::Yoruba => "Yoruba",
            Language::Zulu => "Zulu",
        }
    }

    pub fn google_code(&self) -> &'static str {
        match self {
            Language::Afrikaans => "af",
            Language::Albanian => "sq",
            Language::Amharic => "am",
            Language::Arabic => "ar",
            Language::Armenian => "hy",
            Language::Assamese => "as",
            Language::Aymara => "ay",
            Language::Azerbaijani => "az",
            Language::Bambara => "bm",
            Language::Basque => "eu",
            Language::Belarusian => "be",
            Language::Bengali => "bn",
            Language::Bhojpuri => "bho",
            Language::Bosnian => "bs",
            Language::Bulgarian => "bg",
            Language::Catalan => "ca",
            Language::Cebuano => "ceb",
            Language::ChineseSimplified => "zh-CN",
            Language::ChineseTraditional => "zh-TW",
            Language::Corsican => "co",
            Language::Croatian => "hr",
            Language::Czech => "cs",
            Language::Danish => "da",
            Language::Dhivehi => "dv",
            Language::Dogri => "doi",
            Language::Dutch => "nl",
            Language::English => "en",
            Language::Esperanto => "eo",
            Language::Estonian => "et",
            Language::Ewe => "ee",
            Language::Filipino => "fil",
            Language::Finnish => "fi",
            Language::French => "fr",
            Language::Frisian => "fy",
            Language::Galician => "gl",
            Language::Georgian => "ka",
            Language::German => "de",
            Language::Greek => "el",
            Language::Guarani => "gn",
            Language::Gujarati => "gu",
            Language::HaitianCreole => "ht",
            Language::Hausa => "ha",
            Language::Hawaiian => "haw",
            Language::Hebrew => "he",
            Language::Hindi => "hi",
            Language::Hmong => "hmn",
            Language::Hungarian => "hu",
            Language::Icelandic => "is",
            Language::Igbo => "ig",
            Language::Ilocano => "ilo",
            Language::Indonesian => "id",
            Language::Irish => "ga",
            Language::Italian => "it",
            Language::Japanese => "ja",
            Language::Javanese => "jv",
            Language::Kannada => "kn",
            Language::Kazakh => "kk",
            Language::Khmer => "km",
            Language::Kinyarwanda => "rw",
            Language::Konkani => "kok",
            Language::Korean => "ko",
            Language::Krio => "kri",
            Language::Kurdish => "ku",
            Language::KurdishSorani => "ckb",
            Language::Kyrgyz => "ky",
            Language::Lao => "lo",
            Language::Latin => "la",
            Language::Latvian => "lv",
            Language::Lingala => "ln",
            Language::Lithuanian => "lt",
            Language::Luganda => "lg",
            Language::Luxembourgish => "lb",
            Language::Macedonian => "mk",
            Language::Maithili => "mai",
            Language::Malagasy => "mg",
            Language::Malay => "ms",
            Language::Malayalam => "ml",
            Language::Maltese => "mt",
            Language::Maori => "mi",
            Language::Marathi => "mr",
            Language::Meiteilon => "mni-Mtei",
            Language::Mizo => "lus",
            Language::Mongolian => "mn",
            Language::Myanmar => "my",
            Language::Nepali => "ne",
            Language::Norwegian => "no",
            Language::Nyanja => "ny",
            Language::Odia => "or",
            Language::Oromo => "om",
            Language::Pashto => "ps",
            Language::Persian => "fa",
            Language::Polish => "pl",
            Language::Portuguese => "pt",
            Language::Punjabi => "pa",
            Language::Quechua => "qu",
            Language::Romanian => "ro",
            Language::Russian => "ru",
            Language::Samoan => "sm",
            Language::Sanskrit => "sa",
            Language::ScotsGaelic => "gd",
            Language::Sepedi => "nso",
            Language::Serbian => "sr",
            Language::Sesotho => "st",
            Language::Shona => "sn",
            Language::Sindhi => "sd",
            Language::Sinhala => "si",
            Language::Slovak => "sk",
            Language::Slovenian => "sl",
            Language::Somali => "so",
            Language::Spanish => "es",
            Language::Sundanese => "su",
            Language::Swahili => "sw",
            Language::Swedish => "sv",
            Language::Tajik => "tg",
            Language::Tamil => "ta",
            Language::Tatar => "tt",
            Language::Telugu => "te",
            Language::Thai => "th",
            Language::Tigrinya => "ti",
            Language::Tsonga => "ts",
            Language::Turkish => "tr",
            Language::Turkmen => "tk",
            Language::Twi => "ak",
            Language::Ukrainian => "uk",
            Language::Urdu => "ur",
            Language::Uyghur => "ug",
            Language::Uzbek => "uz",
            Language::Vietnamese => "vi",
            Language::Welsh => "cy",
            Language::Xhosa => "xh",
            Language::Yiddish => "yi",
            Language::Yoruba => "yo",
            Language::Zulu => "zu",
        }
    }
}

impl Language {
    pub fn is_chinese(&self) -> bool {
        matches!(
            self,
            Language::ChineseSimplified | Language::ChineseTraditional
        )
    }

    pub fn all_for_picker() -> Vec<Language> {
        Self::all()
            .into_iter()
            .filter(|l| !l.is_chinese())
            .collect()
    }
}

impl Default for Language {
    fn default() -> Self {
        Language::English
    }
}
